services:
  api:
    image: accountapi:latest
    container_name: accountapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src/main/resources/application.yml:/config/application.yml
      - .:/app
      - maven_data:/root/.m2/repository
    depends_on:
      - database
    ports:
      - ${API_PORT}:${API_PORT}
  database:
    image: postgres:17.2
    container_name: accountapi-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
  maven_data: