spring:
  datasource:
    url: jdbc:postgresql://database/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    clean-disabled: false
    locations: classpath:db/migration
server:
  port: ${API_PORT}