spring:
  application:
    name: accountapi
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration/base
account:
  increase:
    interval: 30s
    coefficient: 1.1
  max-balance-coefficient: 2.07
server:
  servlet:
    context-path: /api/v1
  error:
    include-message: always