spring:
  application:
    name: accountapi
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    locations: classpath:db/migration/base
  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 минут (в ms)

account:
  increase:
    interval: 30s
    coefficient: 1.1
  max-balance-coefficient: 2.07
server:
  servlet:
    context-path: /api/v1
  error:
    include-message: always