spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accountapi_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    clean-disabled: false
    locations: classpath:db/migration, classpath:db/migration/dev