spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accountapi_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    clean-disabled: false
    locations: classpath:db/migration/base, classpath:db/migration/dev
  data:
    redis:
      host: localhost
      port: 6379
jwt:
  secret: 3f4b2a7e8f1c3d2a0b5e6c8f2087a4d9c6e5f0bcb16a14f22986f4084e6c6a2d
  duration: 1d
server:
  port: 8080
logging:
  level:
    root: INFO
    com.fizalise.accountapi: DEBUG